src/Entity/Mineral.php
<?php

namespace App\Entity;

use App\Entity\Coordinate;
use Cocur\Slugify\Slugify;
use ApiPlatform\Metadata\Get;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use App\Repository\MineralRepository;
use ApiPlatform\Metadata\GetCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\Context;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;

#[ApiResource(
    operations: [
        new Get(
            uriTemplate:'minerals/{name}',
            normalizationContext: ['groups' => 'mineral:item:read']
        ),
        new GetCollection(normalizationContext: ['groups' => 'mineral:list:read'])
    ],
    order: ['name' => 'DESC'],
    paginationEnabled: false,
    types: "https://schema.org/Substance"
)]
#[ORM\Entity(repositoryClass: MineralRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields: ['slug'], message: 'This slug already exist')]
class Mineral
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['mineral:list:read', 'mineral:item:read'])]
    #[ApiProperty(identifier: false)]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    #[Assert\Type(
        type: 'string',
        message: 'The value {{ value }} is not a valid {{ type }}.',
    )]
    #[Assert\NotBlank(
        message: 'The name need to be specified'
    )]
    #[Assert\NoSuspiciousCharacters(
        restrictionLevelMessage: 'The name {{ value }} contains non valid caracters'
    )]
    #[Groups(['mineral:list:read', 'mineral:item:read'])]
    #[ApiProperty(types: ['https://schema.org/name'], identifier:true)]
    private ?string $name = null;

    #[ORM\Column(length: 20, nullable: true)]
    #[Assert\Type(
        type: 'string',
        message: 'The value {{ value }} is not a valid {{ type }}.',
    )]
    #[Groups(['mineral:item:read'])]
    #[ApiProperty(types: ['https://schema.org/molecularFormula'])]
    private ?string $formula = null;

    #[ORM\Column(length: 100, nullable: true)]
    #[Assert\Type(
        type: 'string',
        message: 'The value {{ value }} is not a valid {{ type }}.',
    )]
    #[Groups(['mineral:item:read'])]
    private ?string $crystal_system = null;

    #[ORM\Column(type: Types::DECIMAL, nullable: true)]
    #[Assert\Positive]
    #[Groups(['mineral:item:read'])]
    private ?string $density = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Positive]
    #[Assert\Type(
        type: 'integer',
        message: 'The value {{ value }} is not a valid {{ type }}.',
    )]
    #[Groups(['mineral:item:read'])]
    private ?int $hardness = null;

    #[ORM\Column(length: 100, nullable: true)]
    #[Assert\Type(
        type: 'string',
        message: 'The value {{ value }} is not a valid {{ type }}.',
    )]
    #[Groups(['mineral:item:read'])]
    private ?string $fracture = null;

    #[ORM\Column]
    #[Groups(['mineral:list:read', 'mineral:item:read'])]
    #[Context(normalizationContext: [DateTimeNormalizer::FORMAT_KEY => 'd-m-Y'])]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(length: 50, nullable: true)]
    #[Assert\Type(
        type: 'string',
        message: 'The value {{ value }} is not a valid {{ type }}.',
    )]
    #[Groups(['mineral:item:read'])]
    private ?string $streak = null;

    #[ORM\ManyToOne(inversedBy: 'minerals')]
    #[ORM\JoinColumn(nullable: true, onDelete:"SET NULL")]
    #[Groups(['mineral:item:read'])]
    private ?Category $category = null;

    #[ORM\ManyToMany(targetEntity: Color::class, mappedBy: 'minerals')]
    #[Groups(['mineral:item:read'])]
    private Collection $colors;

    #[ORM\ManyToMany(targetEntity: Lustre::class, mappedBy: 'minerals')]
    #[Groups(['mineral:item:read'])]
    private Collection $lustres;

    #[ORM\OneToMany(mappedBy: 'mineral', targetEntity: Variety::class)]
    #[Groups(['mineral:item:read'])]
    private Collection $varieties;

    #[ORM\OneToMany(mappedBy: 'mineral', cascade: ['persist'], orphanRemoval: true, targetEntity: Image::class)]
    #[Groups(['mineral:item:read'])]
    private Collection $images;

    #[ORM\Column(length: 255, unique: true)]
    #[Assert\Type(
        type: 'string',
        message: 'The value is not a valid {{ type }}.',
    )]
    #[Groups(['mineral:list:read', 'mineral:item:read'])]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'mineral', targetEntity: Discussion::class, orphanRemoval: true)]
    private Collection $discussions;

    #[ORM\ManyToMany(targetEntity: Coordinate::class, cascade: ['persist'], inversedBy: 'minerals')]
    #[Groups(['mineral:item:read'])]
    private Collection $coordinates;

    #[ORM\OneToMany(mappedBy: 'mineral', targetEntity: ModificationHistory::class)]
    private Collection $modificationHistories;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Assert\Type(
        type: 'string',
        message: 'The value is not a valid {{ type }}.',
    )]
    #[Groups(['mineral:item:read'])]
    private ?string $description = null;

    #[ORM\OneToMany(mappedBy: 'mineral', targetEntity: Favorite::class, orphanRemoval: true)]
    private Collection $favorites;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['mineral:item:read'])]
    private ?string $image_title = null;

    #[ORM\OneToMany(mappedBy: 'mineral', targetEntity: Contribution::class, orphanRemoval: true)]
    private Collection $contributions;

    public function __construct()
    {
        $this->colors = new ArrayCollection();
        $this->lustres = new ArrayCollection();
        $this->varieties = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable();
        $this->images = new ArrayCollection();
        $this->discussions = new ArrayCollection();
        $this->coordinates = new ArrayCollection();
        $this->modificationHistories = new ArrayCollection();
        $this->favorites = new ArrayCollection();
        $this->contributions = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function prePersist() {
        $this->slug = (new Slugify())->slugify($this->name);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getFormula(): ?string
    {
        return $this->formula;
    }

    public function setFormula(?string $formula): static
    {
        $this->formula = $formula;

        return $this;
    }

    public function getCrystalSystem(): ?string
    {
        return $this->crystal_system;
    }

    public function setCrystalSystem(?string $crystal_system): static
    {
        $this->crystal_system = $crystal_system;

        return $this;
    }

    public function getDensity(): ?string
    {
        return $this->density;
    }

    public function setDensity(?string $density): static
    {
        $this->density = $density;

        return $this;
    }

    public function getHardness(): ?int
    {
        return $this->hardness;
    }

    public function setHardness(?int $hardness): static
    {
        $this->hardness = $hardness;

        return $this;
    }

    public function getFracture(): ?string
    {
        return $this->fracture;
    }

    public function setFracture(?string $fracture): static
    {
        $this->fracture = $fracture;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getStreak(): ?string
    {
        return $this->streak;
    }

    public function setStreak(?string $streak): static
    {
        $this->streak = $streak;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Color>
     */
    public function getColors(): Collection
    {
        return $this->colors;
    }

    public function addColor(Color $color): static
    {
        if (!$this->colors->contains($color)) {
            $this->colors->add($color);
            $color->addMineral($this);
        }

        return $this;
    }

    public function removeColor(Color $color): static
    {
        if ($this->colors->removeElement($color)) {
            $color->removeMineral($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Lustre>
     */
    public function getLustres(): Collection
    {
        return $this->lustres;
    }

    public function addLustre(Lustre $lustre): static
    {
        if (!$this->lustres->contains($lustre)) {
            $this->lustres->add($lustre);
            $lustre->addMineral($this);
        }

        return $this;
    }

    public function removeLustre(Lustre $lustre): static
    {
        if ($this->lustres->removeElement($lustre)) {
            $lustre->removeMineral($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Variety>
     */
    public function getVarieties(): Collection
    {
        return $this->varieties;
    }

    public function addVariety(Variety $variety): static
    {
        if (!$this->varieties->contains($variety)) {
            $this->varieties->add($variety);
            $variety->setMineral($this);
        }

        return $this;

src/Entity/Variety.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use ApiPlatform\Metadata\Get;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use App\Repository\VarietyRepository;
use ApiPlatform\Metadata\GetCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ApiResource(
    operations: [
        new Get(normalizationContext: ['groups' => 'variety:item:read']),
        new GetCollection(normalizationContext: ['groups' => 'variety:list:read'])
    ],
    order: ['name' => 'DESC'],
    paginationEnabled: false,
)]
#[ORM\Entity(repositoryClass: VarietyRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields: ['slug'], message: 'This slug already exist')]
class Variety
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['variety:item:read', 'variety:list:read', 'mineral:item:read'])]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    #[Assert\Type(
        type: 'string',
        message: 'The value {{ value }} is not a valid {{ type }}.',
    )]
    #[Assert\NoSuspiciousCharacters(
        restrictionLevelMessage: 'The name {{ value }} contains non valid caracters'
    )]
    #[Groups(['variety:item:read', 'variety:list:read', 'mineral:item:read'])]
    #[ApiProperty(types: ['https://schema.org/name'])]
    private ?string $name = null;

    #[ORM\ManyToOne(inversedBy: 'varieties')]
    #[ORM\JoinColumn(onDelete:"SET NULL")]
    #[Groups(['variety:item:read'])]
    private ?Mineral $mineral = null;

    #[ORM\OneToMany(mappedBy: 'variety', cascade: ['persist'], orphanRemoval: true, targetEntity: Image::class)]
    #[Groups(['variety:item:read'])]
    private Collection $images;

    #[ORM\Column(length: 255, unique: true)]
    #[Groups(['variety:item:read', 'variety:list:read', 'mineral:item:read'])]
    private ?string $slug = null;

    #[ORM\ManyToMany(targetEntity: Coordinate::class, inversedBy: 'varieties')]
    #[Groups(['variety:item:read', 'mineral:item:read'])]
    private Collection $coordinates;

    #[ORM\OneToMany(mappedBy: 'variety', targetEntity: ModificationHistory::class)]
    private Collection $modificationHistories;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_presentation = null;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->coordinates = new ArrayCollection();
        $this->modificationHistories = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function prePersist() {
        $this->slug = (new Slugify())->slugify($this->name);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getMineral(): ?Mineral
    {
        return $this->mineral;
    }

    public function setMineral(?Mineral $mineral): static
    {
        $this->mineral = $mineral;

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setVariety($this);
        }

        return $this;
    }

    public function removeImage(Image $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getVariety() === $this) {
                $image->setVariety(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Coordinate>
     */
    public function getCoordinates(): Collection
    {
        return $this->coordinates;
    }

    public function addCoordinate(Coordinate $coordinate): static
    {
        if (!$this->coordinates->contains($coordinate)) {
            $this->coordinates->add($coordinate);
        }

        return $this;
    }

    public function removeCoordinate(Coordinate $coordinate): static
    {
        $this->coordinates->removeElement($coordinate);

        return $this;
    }

    /**
     * @return Collection<int, ModificationHistory>
     */
    public function getModificationHistories(): Collection
    {
        return $this->modificationHistories;
    }

    public function addModificationHistory(ModificationHistory $modificationHistory): static
    {
        if (!$this->modificationHistories->contains($modificationHistory)) {
            $this->modificationHistories->add($modificationHistory);
            $modificationHistory->setVariety($this);
        }

        return $this;
    }

    public function removeModificationHistory(ModificationHistory $modificationHistory): static
    {
        if ($this->modificationHistories->removeElement($modificationHistory)) {
            // set the owning side to null (unless already changed)
            if ($modificationHistory->getVariety() === $this) {
                $modificationHistory->setVariety(null);
            }
        }

        return $this;
    }

    public function getImagePresentation(): ?string
    {
        return $this->image_presentation;
    }

    public function setImagePresentation(?string $image_presentation): static
    {
        $this->image_presentation = $image_presentation;

        return $this;
    }
}

templates/wiki/showMineral.html.twig
{% extends 'base.html.twig' %}

{% block title %}Minerals List{% endblock %}

{% block body %}

<div class="mineral-options">
        <a href="{{path('delete_mineral', {'id': mineral.id})}}">Remove this Page</a>
        <a href="{{path('edit_mineral', {'id': mineral.id})}}">Edit this Page</a>
        <a href="#">Discussions</a>
</div>

<h1>
    {{mineral.name}}
    {{mineral.category.name}}
</h1>

<figure id="mineral-figure">
    {% for image in image %}
    <img class="mineral-image" src="{{asset('uploads/images/' ~ image.filename) }}">
    {% endfor %}
</figure>

<section class="section-wiki">
    <h2>Table of Content</h2>

    <div>
        <div>
            <ul>
                <li class="table-list"><a>Varieties of {{mineral.name}}</a></li>
                <li class="table-list"><a>Gallery of {{mineral.name}}</a></li>
                <li class="table-list"></li>
                <li class="table-list"></li>
            </ul>
        </div>
    </div>
    
</section>

<section class="section-wiki">

    <h2>Detailled Caracteristics for {{mineral.name}}</h2>

    <div>
        <p>Formula :{{mineral.formula}}</p>
        <p>Crystal System : {{mineral.crystalSystem}}</p>
        <p>Density : {{mineral.density}}</p>
        <p>Hardness : {{mineral.hardness}}</p>
        <p>Fracture : {{mineral.fracture}}</p>
        <p>Streak : {{mineral.streak}}</p>
    </div>
</section>

<section class="section-wiki">
    <a href="{{ path('new_variety', {'id': mineral.id}) }}">Add a variety</a>
    <h2>Varieties of {{mineral.name}}</h2>

    <div id="varieties-images">
    {% for image in images %}
        <figure class="figure-varieties">
            <img class="mineral-image" src="{{asset('uploads/images/' ~ image.filename) }}">
            <figcaption>{{image.variety.name}}</figcaption>
        </figure>
        
    {% endfor %}
    </div>
</section>

<section class="section-wiki">
    <h2>Images Gallery of {{mineral.name}}</h2>

        <div id="cCarousel">
          <div class="arrow" id="prev"><span class="arrow-symbols">&#8249;</span></div>
          <div class="arrow" id="next"><span class="arrow-symbols">&#8250;</span></div>
        

            <div id="carousel-vp">
                <div id="cCarousel-inner">
        
                {% for image in mineral.images  %}
                    <article class="cCarousel-item">
                        <img class="mineral-image" src="{{asset('uploads/images/' ~ image.filename) }}" alt="Minerals">
                    </article>
                {% endfor %}
                </div>
            </div>
        </div>
</section>

{% endblock %}

templates/wiki/show_mineral_pdf.html.twig
{% block title %}Mineral Details{% endblock %}

{% block body %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
   
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        
        <link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:wght@700&family=Oswald:wght@400;600;700&family=Roboto+Condensed:ital,wght@0,400;0,500;0,600;0,700;1,300&family=Roboto:ital,wght@0,300;0,400;1,300;1,400&display=swap" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="{{ absolute_url(asset('css/pdf.css')) }}">
    </head>
    <body>
        <div class="mineral-options">
            <a role="button" href="">Remove this Page</a>
            <a role="button" href="">Generate a PDF</a>
            <a role="button" href="">Edit this Page</a>
            <a role="button" href="">Discussions</a>
            {% if is_granted('ROLE_ADMIN') %}
                <a role="button" href="">Change Meta Description</a>
            {% endif %}
           
            <a role="button" id="favorite-btn" href="#" data-slug="{{mineral.slug}}">
                Add to favorites <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 576 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M287.9 0c9.2 0 17.6 5.2 21.6 13.5l68.6 141.3 153.2 22.6c9 1.3 16.5 7.6 19.3 16.3s.5 18.1-5.9 24.5L433.6 328.4l26.2 155.6c1.5 9-2.2 18.1-9.6 23.5s-17.3 6-25.3 1.7l-137-73.2L151 509.1c-8.1 4.3-17.9 3.7-25.3-1.7s-11.2-14.5-9.7-23.5l26.2-155.6L31.1 218.2c-6.5-6.4-8.7-15.9-5.9-24.5s10.3-14.9 19.3-16.3l153.2-22.6L266.3 13.5C270.4 5.2 278.7 0 287.9 0zm0 79L235.4 187.2c-3.5 7.1-10.2 12.1-18.1 13.3L99 217.9 184.9 303c5.5 5.5 8.1 13.3 6.8 21L171.4 443.7l105.2-56.2c7.1-3.8 15.6-3.8 22.6 0l105.2 56.2L384.2 324.1c-1.3-7.7 1.2-15.5 6.8-21l85.9-85.1L358.6 200.5c-7.8-1.2-14.6-6.1-18.1-13.3L287.9 79z"/></svg>
            </a>
            
    </div>
    
    <div id="mineral-wrapper">
        <div aria-labelledby="mineral-title" class="mineral-zone">
            <hgroup id="mineral-header">
                <h1 id="mineral-title">{{mineral.name}}<br/></h1>
                {% if mineral.category | length > 0 %}
                    <a href="">{{mineral.category.name}}</a>
                {% else %}
                    <i>Missing information</i>
                {% endif %}
            </hgroup>
            
            <div id="mineral-image-title-zone">
                {% if mineral.imageTitle != null %} 
                <figure id="mineral-figure">
                    <img class="mineral-image" src="{{ absolute_url(asset('uploads/images/' ~ mineral.imageTitle)) }}" alt="Top Image Mineral">
                </figure>
                {% else %}
                    <figure id="mineral-figure">
                        <p>There's no image available</p>
                    </figure>
                {% endif %}
            </div>
            
            <section aria-labelledby="toc-title" class="table-of-content">
                <h2 id="toc-title" >Table of Content</h2>
        
                <div>
                    <div>
                        <ul>
                            <li class="table-list"><a href="#carateristics-heading">Detailled Caracteristics for {{mineral.name}}</a></li>
                            <li class="table-list"><a href="#variety-title">Varieties of {{mineral.name}}</a></li>
                            <li class="table-list"><a href="#section-map-title">Countries where {{mineral.name}} can be found</a></li>
                            <li class="table-list"><a href="#image-gallery-title">Gallery of {{mineral.name}}</a></li>
                        </ul>
                    </div>
                </div>
        
            </section>
    
            <section aria-labelledby="description-mineral-heading" class="section-wiki">
                <div id="description-mineral-wrapper">
                    <div id="description-mineral-header">
                        <h2 id="description-mineral-heading">Description</h2>
                    </div>
                        
                    {% if mineral.description != null %}
                    <div id="description-mineral-body">
                        <p>{{mineral.description}}</p>
                    </div>
                    {% else %}
                    <div id="description-mineral-body">
                        <p>This description section is empty</p>
                    </div>
                    <div id="description-mineral-footer">
                        <a href="">Add a description</a>
                    </div>
                    {% endif %}
                </div>
            </section>
        
            <section class="section-wiki">
        
                <div aria-labelledby="caracteristics-heading" id="caracteristics-wrapper">
                    <h2 id="carateristics-heading">Detailled Caracteristics for {{mineral.name}}</h2>
                    <div id="caracteristics-body">
                        <p>Formula: {{mineral.formula}}</p>
                        <p>Crystal System: {{mineral.crystalSystem}}</p>
                        <p>Density: {{mineral.density}}</p>
                        <p>Hardness: {{mineral.hardness}}</p>
                        <p>Fracture: {{mineral.fracture}}</p>
                        <p>Streak: {{mineral.streak}}</p>
                        <div id="caracteristics-colors">
                            <p>Colors : <br/>
                                {% if mineral.colors | length > 0 %}
                                    {% for color in mineral.colors %}
                                        <a href="">{{color.name}}, </a>
                                    {% endfor %}
                                {% else %}
                                    Missing information
                                {% endif %}
                            </p>
                            <a role="button" class="add-color" href="">Add a color</a>
                        </div>
                        <div id="caracteristics-lustres">
                            <p>Lustres : <br/>
                                {% if mineral.lustres | length > 0 %}
                                    {% for lustre in mineral.lustres %}
                                        <a href="">{{lustre.type}}, </a>
                                    {% endfor %}
                                {% else %}
                                    Missing information
                                {% endif %}
                            </p>
                            <a role="button" aria-role="button" class="add-lustre" href="">Add a lustre</a>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    
    
    <section class="section-wiki">
        <div id="varieties-wrapper">
            <div aria-labelledby="variety-title" id="variety-title-wrapper">
                <hgroup id="variety-title-group">
                    <h2 id="variety-title">Varieties of {{mineral.name}}</h2>
                    <hr>
                </hgroup>
            </div>
            
            <div id="varieties-images">
                {% if varietyImages | length < 0 %}
                    <i>There's no image</i>
                {% endif %}
            {% for image in varietyImages %}
                
                <figure class="figure-varieties">
                {% if image.filename is not null %}
                        <img class="varieties-section-image" src="{{ absolute_url(asset('uploads/images/' ~ image.filename)) }}" alt="Variety Mineral">
                {% else %}
                    <i>Missing image</i>
                {% endif %}
                
                {% if image.variety.name is not null %}
                    <figcaption><a href="">{{image.variety.name}}</a></figcaption>
                {% else %}
                    <i>Missing information</i>
                {% endif %}
                </figure>
    
            {% endfor %}
            </div>
            <div class="varieties-options">
                <a id="add-variety" href="">Add a new variety</a>
                <a href="">Edit Mineral Varieties List</a>
            </div>
        </div>
    </section>
    
    <section aria-labelledby="section-map-title" class="section-map">
        <h2 id="section-map-title" >Countries where {{mineral.name}} can be found</h2>
        <hr>
    
        <div id="mineral-map"></div>
        {% for coordinate in mineral.coordinates %}
        <div class="coordinate-data" data-lat="{{ coordinate.latitude }}" data-lng="{{ coordinate.longitude }}"></div>
        {% endfor %}
        
    </section>
    
    <section class="section-wiki">
        <div aria-labelledby="image-gallery-title" id="carousel-wrapper">
            <h2 id="image-gallery-title">Images Gallery of {{mineral.name}}</h2>
            <hr>
    
            <div id="cCarousel">
              <div class="arrow" id="prev"><span class="arrow-symbols">&#8249;</span></div>
              <div class="arrow" id="next"><span class="arrow-symbols">&#8250;</span></div>
            
    
                <div id="carousel-vp">
                    <div id="cCarousel-inner">
                    {% if mineral.images | length > 0 %}
                        {% for image in mineral.images  %}
                            <figure class="cCarousel-item">
                                <img class="mineral-image" src="{{ absolute_url(asset('uploads/images/' ~ image.filename)) }}" alt="Minerals">
                            </figure>
                        {% endfor %}
                    {% else %}
                        <figure class="cCarousel-item">
                            <p>There's no image in this Gallery</p>
                        </figure>
                    {% endif %}
                    
                    </div>
                </div>
            </div>
        </div>
    </section>
        <script src="/js/carousel.js"></script>
        <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
        crossorigin=""></script>
        <script src="/js/map.js"></script>
        <script src="/js/ajaxFavorite.js"></script>
    </body>
{% endblock %}
</html>